HRINT-3161 Login to docker with secret token

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,10 +7,16 @@ on:
         description: 'RavenDB Version'
         required: true
         type: string
+      docker_user:
+        description: 'DockerHub username'
+        required: false
+        type: string
+        default: ravendb
 
 env:
   IS_NIGHTLY: ${{ contains(inputs.version, 'nightly') }}
-  DOCKER_REPO: 'ravendb/ravendb'
+  DOCKER_USER: ${{ inputs.docker_user }}
+  DOCKER_REPO: '${{ inputs.docker_user }}/ravendb'
 
 jobs:
   linux:
@@ -27,13 +33,13 @@ jobs:
           [[ ${{ env.IS_NIGHTLY }} == true ]] && DOCKER_REPO="$DOCKER_REPO-nightly"
           echo "DOCKER_REPO=$DOCKER_REPO" >> $GITHUB_ENV
 
-      # - name: Login to docker
-      #   run: |
-      #     docker login -u ravendb -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
-      #     if [[ $? -ne 0 ]]; then
-      #       echo "Could not authenticate with Docker Hub"
-      #       exit 1
-      #     fi
+      - name: Login to docker
+        run: |
+          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
+          if [[ $? -ne 0 ]]; then
+            echo "Could not authenticate with Docker Hub"
+            exit 1
+          fi
 
       - uses: actions/checkout@v3
         with:
@@ -70,11 +76,11 @@ jobs:
         working-directory: docker
       - name: Publish package
         run: |
-          pwsh publish-ubuntu.ps1 -Repo $DOCKER_REPO -Arch ${{ matrix.arch }} -DryRun
+          pwsh publish-ubuntu.ps1 -Repo $DOCKER_REPO -Arch ${{ matrix.arch }}
           docker logout
         working-directory: docker
 
-  windowsMatrixCreator:
+  windowsDockerImageBuilder:
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.create.outputs.matrix }}
@@ -90,10 +96,10 @@ jobs:
           fi
 
   windows:
-    needs: windowsMatrixCreator
+    needs: windowsDockerImageBuilder
     strategy:
       matrix:
-        data: ${{ fromJson(needs.windowsMatrixCreator.outputs.matrix) }}
+        data: ${{ fromJson(needs.windowsDockerImageBuilder.outputs.matrix) }}
       fail-fast: false
     runs-on: windows-${{ matrix.data.os }}
     steps:
@@ -105,13 +111,13 @@ jobs:
           [[ ${{ env.IS_NIGHTLY }} == true ]] && DOCKER_REPO="$DOCKER_REPO-nightly"
           echo "DOCKER_REPO=$DOCKER_REPO" >> $GITHUB_ENV
         
-      # - name: Login to docker
-      #   shell: pwsh
-      #   run: |
-      #     docker login -u ravendb -p "${{ secrets.DOCKER_HUB_PASSWORD }}"
-      #     if ($LASTEXITCODE -ne 0) {
-      #       throw "Could not authenticate with Docker Hub"
-      #     }
+      - name: Login to docker
+        shell: pwsh
+        run: |
+          docker login -u ${{ env.DOCKER_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
+          if ($LASTEXITCODE -ne 0) {
+            throw "Could not authenticate with Docker Hub"
+          }
 
       - uses: actions/checkout@v3
         with:
@@ -135,6 +141,6 @@ jobs:
       - name: Publish package
         shell: pwsh
         run: |
-          & .\publish-nanoserver.ps1 -Repo ${{ env.DOCKER_REPO }} -WinVer ${{ matrix.data.winVer }} -DryRun
+          & .\publish-nanoserver.ps1 -Repo ${{ env.DOCKER_REPO }} -WinVer ${{ matrix.data.winVer }}
           docker logout
         working-directory: docker
